apiVersion: v1
kind: Service
metadata:
  name: cogweb
  labels:
    app: cognitiveweb
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the node-web-app service.
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: cognitiveweb
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cogweb
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: sknode
  #   tier: node-web-app
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 2
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: sknode
  #     tier: node-web-app
  template:
    metadata:
      labels:
        app: cognitiveweb
        tier: frontend
    spec:
      containers:
      - name: cogweb
        image: skcontainerregistry-microsoft.azurecr.io/demo/cogweb:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: myregistrykey

